version: "3.7"
services:
  http-certbot:
    image: panac/easy-https
    volumes:
      - certbot:/etc/letsencrypt
    environment:
      DOMAINS: "edrlab.tk www.edrlab.tk"
      EMAIL: pierre.leroux@edrlab.org
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      restart_policy:
        condition: any
    ports:
      - "80:80"
    networks:
      - webnet
  https-nginx:
    image: nginx:1.15
    volumes:
      - ./conf:/etc/nginx/conf.d
      - certbot:/etc/letsencrypt
      - audiobook:/var/www/audiobook
      - php:/var/www/html
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      restart_policy:
        condition: any
    ports:
      - 443:443
    # https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71#ef6e
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - webnet
  ftp:
    image: bogem/ftp
    volumes:
      - audiobook:/home/vsftpd
    environment:
      FTP_USER: eole
      FTP_PASS: b39b4bd4b964526379fefa59fcd03403ae3e2f52a608455f7466c827673a6ed4
      PASV_ADDRESS: "51.159.3.43"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
      restart_policy:
        condition: any
    ports:
      - 20:20
      - 21:21
      - 47400-47470:47400-47470
    networks:
      - webnet
  php:
    image: panac/audiobook-api:v1.1
    volumes:
      - audiobook:/audiobook
      - php:/var/www/html
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
      restart_policy:
        condition: any
    ports:
      - 9000:9000
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: "4096M"
      restart_policy:
        condition: any
    networks:
      - backnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    ports:
      - 9200:9200
    volumes:
      - es:/usr/share/elasticsearch/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: "4096M"
      restart_policy:
        condition: any
    networks:
      - backnet
  opds-server:
    image: panac/opds-server
    ports:
      - 3000:3000
    environment:
      PORT_OPDS_SERVER: 3000
      DOMAIN_OPDS_SERVER: 'edrlab.tk'
      ROOT_OPDS_SERVER: 'api'
      MONGODB_URI: 'mongodb://mongo:27017/webpub'
      ELASTICSEARCH_URI: 'http://elasticsearch:9200'
      NODE_ENV: 'development'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
      restart_policy:
        condition: any
    networks:
      - backnet
      - webnet
  actions-server:
    image: panac/actions-server
    ports:
      - 4000:4000
    environment:
      PORT_ACTIONS_SERVER: 4000
      OPDS_SERVER_URL: 'http://opds-server:3000/webpub'
      COUCHDB_URL: 'http://couchdb:5984'
      NODE_ENV: 'development'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
      restart_policy:
        condition: any
    networks:
      - backnet
      - actionsnet
      - webnet
  couchdb:
    image: couchdb
    ports:
      - 5984:5984
    environment:
      COUCHDB_USER: 'actions'
      COUCHDB_PASSWORD: '123qwe321'
    volumes:
      - couchdb:/opt/couchdb/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "2048M"
      restart_policy:
        condition: any
    networks:
      - actionsnet
networks:
  webnet:
  backnet:
  actionsnet:
volumes:
  certbot:
  audiobook:
  php:
  mongo:
  es:
  couchdb: